const countryFlags = [
  { label: "Afghanistan", value: "🇦🇫" },
  { label: "Albania", value: "🇦🇱" },
  { label: "Algeria", value: "🇩🇿" },
  { label: "American Samoa", value: "🇦🇸" },
  { label: "Andorra", value: "🇦🇩" },
  { label: "Angola", value: "🇦🇴" },
  { label: "Anguilla", value: "🇦🇮" },
  { label: "Antarctica", value: "🇦🇶" },
  { label: "Antigua and Barbuda", value: "🇦🇬" },
  { label: "Argentina", value: "🇦🇷" },
  { label: "Armenia", value: "🇦🇲" },
  { label: "Aruba", value: "🇦🇼" },
  { label: "Australia", value: "🇦🇺" },
  { label: "Austria", value: "🇦🇹" },
  { label: "Azerbaijan", value: "🇦🇿" },
  { label: "Bahamas", value: "🇧🇸" },
  { label: "Bahrain", value: "🇧🇭" },
  { label: "Bangladesh", value: "🇧🇩" },
  { label: "Barbados", value: "🇧🇧" },
  { label: "Belarus", value: "🇧🇾" },
  { label: "Belgium", value: "🇧🇪" },
  { label: "Belize", value: "🇧🇿" },
  { label: "Benin", value: "🇧🇯" },
  { label: "Bermuda", value: "🇧🇲" },
  { label: "Bhutan", value: "🇧🇹" },
  { label: "Bolivia", value: "🇧🇴" },
  { label: "Bosnia and Herzegovina", value: "🇧🇦" },
  { label: "Botswana", value: "🇧🇼" },
  { label: "Brazil", value: "🇧🇷" },
  { label: "British Indian Ocean Territory", value: "🇮🇴" },
  { label: "British Virgin Islands", value: "🇻🇬" },
  { label: "Brunei", value: "🇧🇳" },
  { label: "Bulgaria", value: "🇧🇬" },
  { label: "Burkina Faso", value: "🇧🇫" },
  { label: "Burundi", value: "🇧🇮" },
  { label: "Cambodia", value: "🇰🇭" },
  { label: "Cameroon", value: "🇨🇲" },
  { label: "Canada", value: "🇨🇦" },
  { label: "Cape Verde", value: "🇨🇻" },
  { label: "Cayman Islands", value: "🇰🇾" },
  { label: "Central African Republic", value: "🇨🇫" },
  { label: "Chad", value: "🇹🇩" },
  { label: "Chile", value: "🇨🇱" },
  { label: "China", value: "🇨🇳" },
  { label: "Christmas Island", value: "🇨🇽" },
  { label: "Cocos Islands", value: "🇨🇨" },
  { label: "Colombia", value: "🇨🇴" },
  { label: "Comoros", value: "🇰🇲" },
  { label: "Congo - Brazzaville", value: "🇨🇬" },
  { label: "Congo - Kinshasa", value: "🇨🇩" },
  { label: "Cook Islands", value: "🇨🇰" },
  { label: "Costa Rica", value: "🇨🇷" },
  { label: "Croatia", value: "🇭🇷" },
  { label: "Cuba", value: "🇨🇺" },
  { label: "Curaçao", value: "🇨🇼" },
  { label: "Cyprus", value: "🇨🇾" },
  { label: "Czechia", value: "🇨🇿" },
  { label: "Denmark", value: "🇩🇰" },
  { label: "Djibouti", value: "🇩🇯" },
  { label: "Dominica", value: "🇩🇲" },
  { label: "Dominican Republic", value: "🇩🇴" },
  { label: "Ecuador", value: "🇪🇨" },
  { label: "Egypt", value: "🇪🇬" },
  { label: "El Salvador", value: "🇸🇻" },
  { label: "Equatorial Guinea", value: "🇬🇶" },
  { label: "Eritrea", value: "🇪🇷" },
  { label: "Estonia", value: "🇪🇪" },
  { label: "Eswatini", value: "🇸🇿" },
  { label: "Ethiopia", value: "🇪🇹" },
  { label: "Falkland Islands", value: "🇫🇰" },
  { label: "Faroe Islands", value: "🇫🇴" },
  { label: "Fiji", value: "🇫🇯" },
  { label: "Finland", value: "🇫🇮" },
  { label: "France", value: "🇫🇷" },
  { label: "French Guiana", value: "🇬🇫" },
  { label: "French Polynesia", value: "🇵🇫" },
  { label: "French Southern Territories", value: "🇹🇫" },
  { label: "Gabon", value: "🇬🇦" },
  { label: "Gambia", value: "🇬🇲" },
  { label: "Georgia", value: "🇬🇪" },
  { label: "Germany", value: "🇩🇪" },
  { label: "Ghana", value: "🇬🇭" },
  { label: "Gibraltar", value: "🇬🇮" },
  { label: "Greece", value: "🇬🇷" },
  { label: "Greenland", value: "🇬🇱" },
  { label: "Grenada", value: "🇬🇩" },
  { label: "Guadeloupe", value: "🇬🇵" },
  { label: "Guam", value: "🇬🇺" },
  { label: "Guatemala", value: "🇬🇹" },
  { label: "Guernsey", value: "🇬🇬" },
  { label: "Guinea", value: "🇬🇳" },
  { label: "Guinea-Bissau", value: "🇬🇼" },
  { label: "Guyana", value: "🇬🇾" },
  { label: "Haiti", value: "🇭🇹" },
  { label: "Honduras", value: "🇭🇳" },
  { label: "Hong Kong SAR China", value: "🇭🇰" },
  { label: "Hungary", value: "🇭🇺" },
  { label: "Iceland", value: "🇮🇸" },
  { label: "India", value: "🇮🇳" },
  { label: "Indonesia", value: "🇮🇩" },
  { label: "Iran", value: "🇮🇷" },
  { label: "Iraq", value: "🇮🇶" },
  { label: "Ireland", value: "🇮🇪" },
  { label: "Isle of Man", value: "🇮🇲" },
  { label: "Israel", value: "🇮🇱" },
  { label: "Italy", value: "🇮🇹" },
  { label: "Jamaica", value: "🇯🇲" },
  { label: "Japan", value: "🇯🇵" },
  { label: "Jersey", value: "🇯🇪" },
  { label: "Jordan", value: "🇯🇴" },
  { label: "Kazakhstan", value: "🇰🇿" },
  { label: "Kenya", value: "🇰🇪" },
  { label: "Kiribati", value: "🇰🇮" },
  { label: "Kosovo", value: "🇽🇰" },
  { label: "Kuwait", value: "🇰🇼" },
  { label: "Kyrgyzstan", value: "🇰🇬" },
  { label: "Laos", value: "🇱🇦" },
  { label: "Latvia", value: "🇱🇻" },
  { label: "Lebanon", value: "🇱🇧" },
  { label: "Lesotho", value: "🇱🇸" },
  { label: "Liberia", value: "🇱🇷" },
  { label: "Libya", value: "🇱🇾" },
  { label: "Liechtenstein", value: "🇱🇮" },
  { label: "Lithuania", value: "🇱🇹" },
  { label: "Luxembourg", value: "🇱🇺" },
  { label: "Macau SAR China", value: "🇲🇴" },
  { label: "Madagascar", value: "🇲🇬" },
  { label: "Malawi", value: "🇲🇼" },
  { label: "Malaysia", value: "🇲🇾" },
  { label: "Maldives", value: "🇲🇻" },
  { label: "Mali", value: "🇲🇱" },
  { label: "Malta", value: "🇲🇹" },
  { label: "Marshall Islands", value: "🇲🇭" },
  { label: "Martinique", value: "🇲🇶" },
  { label: "Mauritania", value: "🇲🇷" },
  { label: "Mauritius", value: "🇲🇺" },
  { label: "Mayotte", value: "🇾🇹" },
  { label: "Mexico", value: "🇲🇽" },
  { label: "Micronesia", value: "🇫🇲" },
  { label: "Moldova", value: "🇲🇩" },
  { label: "Monaco", value: "🇲🇨" },
  { label: "Mongolia", value: "🇲🇳" },
  { label: "Montenegro", value: "🇲🇪" },
  { label: "Montserrat", value: "🇲🇸" },
  { label: "Morocco", value: "🇲🇦" },
  { label: "Mozambique", value: "🇲🇿" },
  { label: "Myanmar", value: "🇲🇲" },
  { label: "Namibia", value: "🇳🇦" },
  { label: "Nauru", value: "🇳🇷" },
  { label: "Nepal", value: "🇳🇵" },
  { label: "Netherlands", value: "🇳🇱" },
  { label: "New Caledonia", value: "🇳🇨" },
  { label: "New Zealand", value: "🇳🇿" },
  { label: "Nicaragua", value: "🇳🇮" },
  { label: "Niger", value: "🇳🇪" },
  { label: "Nigeria", value: "🇳🇬" },
  { label: "Niue", value: "🇳🇺" },
  { label: "Norfolk Island", value: "🇳🇫" },
  { label: "North Korea", value: "🇰🇵" },
  { label: "North Macedonia", value: "🇲🇰" },
  { label: "Northern Mariana Islands", value: "🇲🇵" },
  { label: "Norway", value: "🇳🇴" },
  { label: "Oman", value: "🇴🇲" },
  { label: "Pakistan", value: "🇵🇰" },
  { label: "Palau", value: "🇵🇼" },
  { label: "Palestinian Territories", value: "🇵🇸" },
  { label: "Panama", value: "🇵🇦" },
  { label: "Papua New Guinea", value: "🇵🇬" },
  { label: "Paraguay", value: "🇵🇾" },
  { label: "Peru", value: "🇵🇪" },
  { label: "Philippines", value: "🇵🇭" },
  { label: "Pitcairn Islands", value: "🇵🇳" },
  { label: "Poland", value: "🇵🇱" },
  { label: "Portugal", value: "🇵🇹" },
  { label: "Puerto Rico", value: "🇵🇷" },
  { label: "Qatar", value: "🇶🇦" },
  { label: "Réunion", value: "🇷🇪" },
  { label: "Romania", value: "🇷🇴" },
  { label: "Russia", value: "🇷🇺" },
  { label: "Rwanda", value: "🇷🇼" },
  { label: "Samoa", value: "🇼🇸" },
  { label: "San Marino", value: "🇸🇲" },
  { label: "São Tomé and Príncipe", value: "🇸🇹" },
  { label: "Saudi Arabia", value: "🇸🇦" },
  { label: "Senegal", value: "🇸🇳" },
  { label: "Serbia", value: "🇷🇸" },
  { label: "Seychelles", value: "🇸🇨" },
  { label: "Sierra Leone", value: "🇸🇱" },
  { label: "Singapore", value: "🇸🇬" },
  { label: "Sint Maarten", value: "🇸🇽" },
  { label: "Slovakia", value: "🇸🇰" },
  { label: "Slovenia", value: "🇸🇮" },
  { label: "Solomon Islands", value: "🇸🇧" },
  { label: "Somalia", value: "🇸🇴" },
  { label: "South Africa", value: "🇿🇦" },
  { label: "South Georgia & South Sandwich Islands", value: "🇬🇸" },
  { label: "South Korea", value: "🇰🇷" },
  { label: "South Sudan", value: "🇸🇸" },
  { label: "Spain", value: "🇪🇸" },
  { label: "Sri Lanka", value: "🇱🇰" },
  { label: "St. Barthélemy", value: "🇧🇱" },
  { label: "St. Helena", value: "🇸🇭" },
  { label: "St. Kitts & Nevis", value: "🇰🇳" },
  { label: "St. Lucia", value: "🇱🇨" },
  { label: "St. Martin", value: "🇲🇫" },
  { label: "St. Pierre & Miquelon", value: "🇵🇲" },
  { label: "St. Vincent & Grenadines", value: "🇻🇨" },
  { label: "Sudan", value: "🇸🇩" },
  { label: "Suriname", value: "🇸🇷" },
  { label: "Sweden", value: "🇸🇪" },
  { label: "Switzerland", value: "🇨🇭" },
  { label: "Syria", value: "🇸🇾" },
  { label: "Taiwan", value: "🇹🇼" },
  { label: "Tajikistan", value: "🇹🇯" },
  { label: "Tanzania", value: "🇹🇿" },
  { label: "Thailand", value: "🇹🇭" },
  { label: "Timor-Leste", value: "🇹🇱" },
  { label: "Togo", value: "🇹🇬" },
  { label: "Tokelau", value: "🇹🇰" },
  { label: "Tonga", value: "🇹🇴" },
  { label: "Trinidad & Tobago", value: "🇹🇹" },
  { label: "Tunisia", value: "🇹🇳" },
  { label: "Turkey", value: "🇹🇷" },
  { label: "Turkmenistan", value: "🇹🇲" },
  { label: "Turks & Caicos Islands", value: "🇹🇨" },
  { label: "Tuvalu", value: "🇹🇻" },
  { label: "Uganda", value: "🇺🇬" },
  { label: "Ukraine", value: "🇺🇦" },
  { label: "United Arab Emirates", value: "🇦🇪" },
  { label: "United Kingdom", value: "🇬🇧" },
  { label: "United States", value: "🇺🇸" },
  { label: "Uruguay", value: "🇺🇾" },
  { label: "Uzbekistan", value: "🇺🇿" },
  { label: "Vanuatu", value: "🇻🇺" },
  { label: "Vatican City", value: "🇻🇦" },
  { label: "Venezuela", value: "🇻🇪" },
  { label: "Vietnam", value: "🇻🇳" },
  { label: "Wallis & Futuna", value: "🇼🇫" },
  { label: "Western Sahara", value: "🇪🇭" },
  { label: "Yemen", value: "🇾🇪" },
  { label: "Zambia", value: "🇿🇲" },
  { label: "Zimbabwe", value: "🇿🇼" },
];

export default countryFlags;
