import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import ScrollAreaY from "~/app/_ui/scrollAreaY";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`h-dvh font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <main className="flex h-full flex-col items-center justify-center overflow-y-auto bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
            <ScrollAreaY className="!bottom-[72px] !top-[72px] md:!bottom-0">
              {children}
            </ScrollAreaY>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
